In [1]:
import sqlite3
from sqlite3 import Error

In [2]:
#task 10
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT name AS facility,
	SUM(CASE WHEN Bookings.memid = 0 THEN ROUND(guestcost*slots,2)
	WHEN Bookings.memid <> 0 THEN ROUND(membercost*slots,2) END) AS total_revenue
FROM Bookings
LEFT JOIN Facilities
	ON Bookings.facid = Facilities.facid
WHERE guestcost*slots < 1000
	OR membercost*slots < 1000
GROUP BY name
ORDER BY total_revenue DESC;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("10. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
10. Query all tasks
('Massage Room 1', 50351.600000000275)
('Massage Room 2', 14454.599999999995)
('Tennis Court 2', 14310.0)
('Tennis Court 1', 13860.0)
('Squash Court', 13468.0)
('Badminton Court', 1906.5)
('Pool Table', 270.0)
('Snooker Table', 240.0)
('Table Tennis', 180.0)

In [3]:
#task 11
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT m1.surname,m1.firstname,m2.surname AS surname_recommendedby, m2.firstname AS firstname_recommendedby
FROM Members AS m1
INNER JOIN Members AS m2
	ON m1.recommendedby = m2.memid
WHERE m1.memid <> 0
ORDER BY m2.surname,m2.firstname;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("11. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
11. Query all tasks
('Sarwin', 'Ramnaresh', 'Bader', 'Florence')
('Coplin', 'Joan', 'Baker', 'Timothy')
('Genting', 'Matthew', 'Butters', 'Gerald')
('Baker', 'Timothy', 'Farrell', 'Jemima')
('Pinker', 'David', 'Farrell', 'Jemima')
('Rumney', 'Henrietta', 'Genting', 'Matthew')
('Jones', 'Douglas', 'Jones', 'David')
('Dare', 'Nancy', 'Joplette', 'Janice')
('Jones', 'David', 'Joplette', 'Janice')
('Hunt', 'John', 'Purview', 'Millicent')
('Boothe', 'Tim', 'Rownam', 'Tim')
('Joplette', 'Janice', 'Smith', 'Darren')
('Butters', 'Gerald', 'Smith', 'Darren')
('Owen', 'Charles', 'Smith', 'Darren')
('Smith', 'Jack', 'Smith', 'Darren')
('Mackenzie', 'Anna', 'Smith', 'Darren')
('Worthington-Smyth', 'Henry', 'Smith', 'Tracy')
('Purview', 'Millicent', 'Smith', 'Tracy')
('Crumpet', 'Erica', 'Smith', 'Tracy')
('Baker', 'Anne', 'Stibbons', 'Ponder')
('Bader', 'Florence', 'Stibbons', 'Ponder')
('Stibbons', 'Ponder', 'Tracy', 'Burton')

In [4]:
#task 12
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT facid, memid, COUNT(bookid)
FROM Bookings
WHERE memid != 0
GROUP BY facid,memid;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("12. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
12. Query all tasks
(0, 2, 30)
(0, 3, 6)
(0, 4, 19)
(0, 5, 57)
(0, 6, 31)
(0, 7, 25)
(0, 8, 4)
(0, 9, 1)
(0, 10, 17)
(0, 11, 25)
(0, 12, 6)
(0, 13, 1)
(0, 14, 22)
(0, 15, 1)
(0, 16, 14)
(0, 17, 16)
(0, 20, 1)
(0, 22, 7)
(0, 24, 5)
(0, 26, 9)
(0, 28, 6)
(0, 35, 4)
(0, 36, 1)
(1, 1, 19)
(1, 2, 2)
(1, 3, 6)
(1, 4, 8)
(1, 5, 3)
(1, 6, 3)
(1, 7, 11)
(1, 8, 52)
(1, 9, 31)
(1, 10, 41)
(1, 11, 30)
(1, 12, 35)
(1, 13, 1)
(1, 14, 1)
(1, 15, 8)
(1, 16, 7)
(1, 24, 11)
(1, 27, 1)
(1, 28, 1)
(1, 30, 1)
(1, 35, 4)
(2, 1, 132)
(2, 2, 32)
(2, 3, 4)
(2, 5, 20)
(2, 6, 2)
(2, 7, 10)
(2, 8, 12)
(2, 9, 16)
(2, 10, 6)
(2, 11, 8)
(2, 12, 10)
(2, 13, 7)
(2, 14, 12)
(2, 15, 9)
(2, 16, 7)
(2, 17, 7)
(2, 21, 30)
(2, 24, 7)
(2, 26, 2)
(2, 29, 4)
(2, 30, 2)
(2, 33, 1)
(2, 35, 2)
(2, 36, 2)
(3, 1, 28)
(3, 2, 28)
(3, 3, 69)
(3, 4, 9)
(3, 5, 1)
(3, 6, 24)
(3, 7, 5)
(3, 8, 4)
(3, 9, 3)
(3, 10, 24)
(3, 11, 11)
(3, 12, 1)
(3, 13, 12)
(3, 14, 5)
(3, 15, 42)
(3, 16, 24)
(3, 17, 17)
(3, 20, 26)
(3, 21, 16)
(3, 22, 21)
(3, 24, 3)
(3, 29, 3)
(3, 30, 6)
(3, 35, 1)
(3, 36, 2)
(4, 1, 28)
(4, 2, 6)
(4, 3, 80)
(4, 4, 12)
(4, 5, 32)
(4, 6, 31)
(4, 7, 19)
(4, 8, 36)
(4, 9, 19)
(4, 10, 11)
(4, 11, 19)
(4, 12, 3)
(4, 13, 29)
(4, 14, 27)
(4, 16, 24)
(4, 17, 3)
(4, 20, 25)
(4, 21, 1)
(4, 22, 1)
(4, 24, 8)
(4, 29, 1)
(4, 33, 1)
(4, 35, 3)
(4, 36, 2)
(5, 3, 2)
(5, 4, 2)
(5, 5, 1)
(5, 7, 5)
(5, 10, 2)
(5, 11, 4)
(5, 12, 2)
(5, 14, 1)
(5, 15, 2)
(5, 20, 1)
(5, 22, 2)
(5, 24, 3)
(6, 1, 14)
(6, 2, 6)
(6, 4, 14)
(6, 5, 9)
(6, 6, 35)
(6, 8, 12)
(6, 9, 2)
(6, 10, 7)
(6, 11, 8)
(6, 12, 49)
(6, 13, 8)
(6, 14, 9)
(6, 15, 2)
(6, 16, 5)
(6, 17, 3)
(6, 21, 2)
(6, 22, 1)
(6, 24, 2)
(6, 26, 1)
(6, 27, 2)
(6, 28, 1)
(6, 30, 1)
(6, 33, 1)
(6, 35, 1)
(7, 1, 12)
(7, 2, 45)
(7, 4, 68)
(7, 5, 34)
(7, 6, 20)
(7, 7, 23)
(7, 8, 43)
(7, 9, 20)
(7, 10, 22)
(7, 11, 2)
(7, 13, 21)
(7, 14, 5)
(7, 15, 33)
(7, 17, 16)
(7, 20, 1)
(7, 21, 7)
(7, 22, 10)
(7, 24, 18)
(7, 27, 14)
(7, 28, 1)
(7, 30, 1)
(7, 33, 5)
(8, 1, 28)
(8, 2, 61)
(8, 3, 241)
(8, 4, 27)
(8, 5, 6)
(8, 6, 30)
(8, 7, 19)
(8, 8, 25)
(8, 9, 12)
(8, 10, 1)
(8, 11, 8)
(8, 12, 12)
(8, 13, 1)
(8, 14, 7)
(8, 15, 23)
(8, 16, 85)
(8, 17, 9)
(8, 20, 18)
(8, 21, 70)
(8, 22, 11)
(8, 24, 13)
(8, 26, 2)
(8, 27, 3)
(8, 28, 25)
(8, 29, 33)
(8, 30, 5)
(8, 33, 8)

In [5]:
#task 13 (this works on the other server)
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT EXTRACT(MONTH FROM starttime) AS month, 
    facid, 
    COUNT(bookid)
FROM Bookings
WHERE memid != 0
GROUP BY month, facid;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("13. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
13. Query all tasks

OperationalError: near "FROM": syntax error